name: Build Neovide on ARM64 Ubuntu

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref to build (e.g., refs/tags/0.12.1)"
        required: true
        default: "refs/tags/0.12.1"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: rustup target add aarch64-unknown-linux-gnu

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          appstream \
          ca-certificates \
          cmake \
          curl \
          file \
          g++-multilib \
          gcc-multilib \
          git \
          gnupg \
          libbz2-dev \
          libexpat1-dev \
          libfontconfig-dev \
          libfreetype6-dev \
          libfuse2 \
          libpng16-16 \
          libssl-dev \
          libxcb-composite0-dev \
          libxi-dev \
          pkg-config \
          clang \
          libxcb-render0-dev \
          libxcb-shape0-dev \
          libxcb-xfixes0-dev \
          libfontconfig1-dev \
          libfreetype6-dev \
          libx11-xcb-dev \
          libxcb-keysyms1-dev \
          libxcb-randr0-dev \
          libxcb-composite0-dev \
          libxcb-image0-dev \
          libxcb-present-dev \
          libxkbcommon-dev \
          libxkbcommon-x11-dev \
          libxkbfile-dev \
          libc++-dev \
          libc++abi-dev

      - name: Build Neovide
        run: |
          cargo build --release --target aarch64-unknown-linux-gnu --keep-going

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: neovide-artifacts
          path: target/release
