name: Build Neovide on ARM64 Ubuntu

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-20.04]
        arch: [arm64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: 'refs/tags/0.12.1'

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Build Neovide
        run: |
          cargo build --release
